name: PR Check 69

on:
  push:
    branches: [ too-many-PR-checks ]
  pull_request:
    branches: [ too-many-PR-checks ]

  workflow_dispatch:

jobs:
  check-69:
    runs-on: ubuntu-latest

    steps:
      - run: echo "check 69 passed"
