name: PR Check 47

on:
  push:
    branches: [ too-many-PR-checks ]
  pull_request:
    branches: [ too-many-PR-checks ]

  workflow_dispatch:

jobs:
  check-47:
    runs-on: ubuntu-latest

    steps:
      - run: echo "check 47 passed"
