name: PR Check 24

on:
  push:
    branches: [ too-many-PR-checks ]
  pull_request:
    branches: [ too-many-PR-checks ]

  workflow_dispatch:

jobs:
  check-24:
    runs-on: ubuntu-latest

    steps:
      - run: echo "check 24 passed"
