name: PR Check 15

on:
  push:
    branches: [ too-many-PR-checks ]
  pull_request:
    branches: [ too-many-PR-checks ]

  workflow_dispatch:

jobs:
  check-15:
    runs-on: ubuntu-latest

    steps:
      - run: echo "check 15 passed"
