name: PR Check 18

on:
  push:
    branches: [ too-many-PR-checks ]
  pull_request:
    branches: [ too-many-PR-checks ]

  workflow_dispatch:

jobs:
  check-18:
    runs-on: ubuntu-latest

    steps:
      - run: echo "check 18 passed"
