name: PR Check 58

on:
  push:
    branches: [ too-many-PR-checks ]
  pull_request:
    branches: [ too-many-PR-checks ]

  workflow_dispatch:

jobs:
  check-58:
    runs-on: ubuntu-latest

    steps:
      - run: echo "check 58 passed"
