name: PR Check 87

on:
  push:
    branches: [ too-many-PR-checks ]
  pull_request:
    branches: [ too-many-PR-checks ]

  workflow_dispatch:

jobs:
  check-87:
    runs-on: ubuntu-latest

    steps:
      - run: echo "check 87 passed"
